import React, { useState, useEffect, useRef } from 'react';
import { useLocation } from 'react-router-dom';
import {
  Bot, User, Send, Zap, BookOpen, BookmarkCheck, Download,
  Loader2, CheckCircle2, Info
} from 'lucide-react';
import api from '../api';

interface AnalysisResult {
  analysis: string;
  keywords: string[];
  title?: string;
  authors?: string;
}

interface Message {
  role: 'user' | 'sys';
  text: string;
}

const AIChat = () => {
  const location = useLocation();
  const statePaperText = location.state?.paperText || '';
  const statePaperTitle = location.state?.paperTitle || '';

  const [messages, setMessages] = useState<Message[]>([
    { role: 'sys', text: 'AI Agent initialized. Ready to assist with research analysis and literature queries.' }
  ]);
  const [inputVal, setInputVal] = useState('');
  const [loading, setLoading] = useState(false);
  const [paperInput, setPaperInput] = useState(statePaperText);
  const [analysisResult, setAnalysisResult] = useState<AnalysisResult | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [activeTab, setActiveTab] = useState<'chat' | 'analysis'>('chat');
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [paperContextActive, setPaperContextActive] = useState(!!statePaperText);
  const [saveSuccess, setSaveSuccess] = useState(false);

  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, analysisResult]);

  // If paper context was passed via navigation, show info
  useEffect(() => {
    if (statePaperText && statePaperTitle) {
      setMessages(prev => [...prev, {
        role: 'sys',
        text: `📄 Paper context loaded: "${statePaperTitle}". I'm now primed to answer questions specifically about this paper.`
      }]);
    }
  }, []); // only on mount

  const handleSendChat = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputVal.trim()) return;

    const userMsg = inputVal;
    setInputVal('');
    setMessages(prev => [...prev, { role: 'user', text: userMsg }]);
    setLoading(true);

    try {
      const payload: { message: string; paper_context?: string } = { message: userMsg };
      if (paperContextActive && paperInput.trim()) {
        payload.paper_context = paperInput;
      }
      const res = await api.post('/chat', payload);
      setMessages(prev => [...prev, { role: 'sys', text: res.data.reply }]);
    } catch (err) {
      setMessages(prev => [...prev, { role: 'sys', text: 'Error connecting to the AI core.' }]);
    } finally {
      setLoading(false);
    }
  };

  const handleAnalyzePaper = async () => {
    if (!paperInput.trim()) return;
    setAnalyzing(true);
    setAnalysisResult(null);
    setSaved(false);
    setSaveSuccess(false);
    try {
      const res = await api.post('/analyze-paper', { text: paperInput });
      setAnalysisResult(res.data);
      setActiveTab('analysis');
      setPaperContextActive(true);
    } catch (err) {
      console.error(err);
      alert('Failed to analyze paper.');
    } finally {
      setAnalyzing(false);
    }
  };

  const handleSaveAnalysis = async () => {
    if (!analysisResult) return;
    setSaving(true);
    try {
      await api.post('/saved-analyses', {
        title: analysisResult.title || 'Untitled Analysis',
        authors: analysisResult.authors || '',
        abstract: paperInput.slice(0, 500), // save first 500 chars as abstract
        summary: analysisResult.analysis,
        keywords: analysisResult.keywords.join(', '),
      });
      setSaved(true);
      setSaveSuccess(true);
      setTimeout(() => setSaveSuccess(false), 3000);
    } catch (err) {
      console.error('Save failed:', err);
      alert('Failed to save analysis.');
    } finally {
      setSaving(false);
    }
  };

  const handleExport = () => {
    if (!analysisResult) return;
    const md = [
      `# Analysis: ${analysisResult.title || 'Research Paper'}`,
      analysisResult.authors ? `**Authors:** ${analysisResult.authors}` : '',
      '',
      '## Summary & Findings',
      analysisResult.analysis,
      '',
      '## Keywords',
      analysisResult.keywords.map(k => `- ${k}`).join('\n'),
      '',
      `---\n*Generated by ResearchHub AI — ${new Date().toLocaleString()}*`,
    ].join('\n');

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `analysis-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const tabBtnStyle = (active: boolean) => ({
    flex: 1,
    padding: '1rem',
    background: active ? 'rgba(88, 166, 255, 0.1)' : 'transparent',
    color: active ? 'var(--primary-color)' : 'var(--text-primary)',
    border: 'none',
    borderBottom: active ? '2px solid var(--primary-color)' : '2px solid transparent',
    cursor: 'pointer',
    fontWeight: 500 as const,
    transition: 'all 0.2s',
    display: 'flex' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: '0.5rem',
  });

  return (
    <div className="animate-fade-in" style={{ display: 'grid', gridTemplateColumns: 'minmax(300px, 1fr) 2fr', gap: '2rem' }}>

      {/* ── Sidebar ── */}
      <div className="glass-panel" style={{ display: 'flex', flexDirection: 'column', padding: '1.5rem', gap: '1rem', height: 'fit-content' }}>
        <h3 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0' }}>
          <BookOpen size={20} /> Content Analyzer
        </h3>
        <p style={{ fontSize: '0.875rem', color: 'var(--secondary-color)', margin: 0 }}>
          Paste paper abstract or full text for deep AI extraction — summary, findings, research questions, and keywords.
        </p>

        <textarea
          className="input-field"
          placeholder="Paste scientific text here..."
          value={paperInput}
          onChange={(e) => setPaperInput(e.target.value)}
          style={{ minHeight: '200px', fontSize: '0.875rem', marginBottom: 0 }}
        />

        <button
          className="btn btn-primary"
          onClick={handleAnalyzePaper}
          disabled={analyzing || !paperInput.trim()}
          id="run-analysis-btn"
        >
          {analyzing ? <Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} /> : <><Zap size={16} /> Run Analysis</>}
        </button>

        {/* Paper context toggle */}
        {paperInput.trim() && (
          <label style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', fontSize: '0.85rem', color: 'var(--secondary-color)', cursor: 'pointer' }}>
            <input
              type="checkbox"
              checked={paperContextActive}
              onChange={e => setPaperContextActive(e.target.checked)}
              style={{ accentColor: 'var(--primary-color)' }}
            />
            Prime chat with this paper
          </label>
        )}

        {paperContextActive && paperInput.trim() && (
          <div style={{ display: 'flex', alignItems: 'flex-start', gap: '0.5rem', padding: '0.75rem', background: 'rgba(88, 166, 255, 0.07)', borderRadius: '8px', border: '1px solid rgba(88, 166, 255, 0.2)' }}>
            <Info size={14} style={{ color: 'var(--primary-color)', marginTop: '2px', flexShrink: 0 }} />
            <p style={{ margin: 0, fontSize: '0.8rem', color: 'var(--primary-color)', lineHeight: 1.4 }}>
              Chat is now primed with the paper context. AI answers will reference the loaded paper.
            </p>
          </div>
        )}

        {/* Save & Export actions */}
        {analysisResult && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem', paddingTop: '0.5rem', borderTop: '1px solid var(--border-color)' }}>
            <button
              className="btn"
              onClick={handleSaveAnalysis}
              disabled={saving || saved}
              id="save-analysis-btn"
              style={{
                borderColor: saveSuccess ? 'var(--success-color)' : undefined,
                color: saveSuccess ? 'var(--success-color)' : undefined,
              }}
            >
              {saving
                ? <Loader2 size={14} style={{ animation: 'spin 1s linear infinite' }} />
                : saveSuccess
                  ? <><CheckCircle2 size={14} /> Saved!</>
                  : <><BookmarkCheck size={14} /> Save Analysis</>
              }
            </button>

            <button
              className="btn"
              onClick={handleExport}
              id="export-analysis-btn"
            >
              <Download size={14} /> Export Markdown
            </button>
          </div>
        )}
      </div>

      {/* ── Main Panel ── */}
      <div className="glass-panel chat-container" style={{ padding: 0, overflow: 'hidden' }}>
        {/* Tabs */}
        <div style={{ display: 'flex', borderBottom: '1px solid var(--border-color)', background: 'rgba(13, 17, 23, 0.4)' }}>
          <button style={tabBtnStyle(activeTab === 'chat')} onClick={() => setActiveTab('chat')} id="tab-chat">
            <Bot size={18} /> General Chat
          </button>
          <button style={tabBtnStyle(activeTab === 'analysis')} onClick={() => setActiveTab('analysis')} id="tab-analysis">
            <Zap size={18} /> Analysis Results
          </button>
        </div>

        {/* ── Chat Tab ── */}
        {activeTab === 'chat' ? (
          <>
            <div className="chat-messages">
              {messages.map((msg, idx) => (
                <div key={idx} className={`chat-msg ${msg.role === 'user' ? 'msg-user' : 'msg-ai'}`}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', color: msg.role === 'user' ? 'var(--primary-color)' : 'var(--secondary-color)', fontSize: '0.85rem', fontWeight: 600 }}>
                    {msg.role === 'user' ? <User size={14} /> : <Bot size={14} />}
                    {msg.role === 'user' ? 'You' : 'AI Agent'}
                  </div>
                  <div style={{ whiteSpace: 'pre-wrap' }}>{msg.text}</div>
                </div>
              ))}
              {loading && (
                <div className="chat-msg msg-ai">
                  <Loader2 size={16} style={{ color: 'var(--primary-color)', animation: 'spin 1s linear infinite' }} />
                </div>
              )}
              <div ref={bottomRef} />
            </div>

            <form onSubmit={handleSendChat} className="chat-input-area" style={{ padding: '1rem', background: 'rgba(13, 17, 23, 0.4)' }}>
              <input
                type="text"
                id="chat-input"
                className="input-field"
                style={{ marginBottom: 0 }}
                placeholder={paperContextActive ? 'Ask about the loaded paper...' : 'Ask about research methodology, literature...'}
                value={inputVal}
                onChange={e => setInputVal(e.target.value)}
              />
              <button type="submit" className="btn btn-primary" disabled={loading || !inputVal.trim()} style={{ padding: '0 1.5rem' }} id="send-msg-btn">
                <Send size={18} />
              </button>
            </form>
          </>
        ) : (
          /* ── Analysis Tab ── */
          <div className="chat-messages" style={{ background: 'rgba(13, 17, 23, 0.4)' }}>
            {!analysisResult && !analyzing && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--secondary-color)' }}>
                <Zap size={48} style={{ opacity: 0.3, marginBottom: '1rem' }} />
                <p>Run analysis on a paper to see results here.</p>
              </div>
            )}

            {analyzing && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--primary-color)' }}>
                <Loader2 size={48} style={{ animation: 'spin 1s linear infinite', marginBottom: '1rem' }} />
                <p className="animate-fade-in">Processing semantic analysis...</p>
              </div>
            )}

            {analysisResult && (
              <div className="animate-fade-in" style={{ padding: '0.5rem' }}>
                {/* Title & Authors */}
                {(analysisResult.title || analysisResult.authors) && (
                  <div style={{ marginBottom: '1.5rem', padding: '1rem', background: 'rgba(88, 166, 255, 0.05)', borderRadius: '10px', border: '1px solid rgba(88, 166, 255, 0.15)' }}>
                    {analysisResult.title && (
                      <h4 style={{ color: 'var(--text-heading)', marginBottom: '0.25rem' }}>{analysisResult.title}</h4>
                    )}
                    {analysisResult.authors && (
                      <p style={{ color: 'var(--secondary-color)', fontSize: '0.875rem', margin: 0 }}>{analysisResult.authors}</p>
                    )}
                  </div>
                )}

                {/* Summary */}
                <div style={{ marginBottom: '2rem' }}>
                  <h4 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--primary-color)', marginBottom: '0.75rem' }}>
                    <Bot size={18} /> Comprehensive Analysis
                  </h4>
                  <div className="msg-ai" style={{ padding: '1.5rem', borderRadius: '12px', whiteSpace: 'pre-wrap', lineHeight: 1.7 }}>
                    {analysisResult.analysis}
                  </div>
                </div>

                {/* Keywords */}
                {analysisResult.keywords.length > 0 && (
                  <div>
                    <h4 style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--primary-color)', marginBottom: '0.75rem' }}>
                      <Zap size={18} /> Extracted Keywords
                    </h4>
                    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                      {analysisResult.keywords.map((kw, i) => (
                        <span key={i} className="badge">{kw.trim()}</span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )}
            <div ref={bottomRef} />
          </div>
        )}
      </div>
    </div>
  );
};

export default AIChat;
